
usethis::use_package("usethis")
usethis::use_package("shiny")
usethis::use_package("shinyjs")
usethis::use_package("devtools")
usethis::use_package("purrr")
usethis::use_package("Rscience.import")
usethis::use_package("Rscience.menu")
usethis::use_package("openxlsx")
usethis::use_package("colourpicker")
usethis::use_package("readxl")
usethis::use_package("shinyAce")
usethis::use_package("quarto")
usethis::use_package("car")
usethis::use_package("DT")
usethis::use_package("shinycssloaders")
usethis::use_package("EnvStats")
usethis::use_package("shinyjs")
usethis::use_package("crayon")
usethis::use_package("stringi")
usethis::use_package("plotly")
usethis::use_package("kableExtra")
usethis::use_package("Hmisc")
usethis::use_package("reshape2")


usethis::use_package("dplyr")
usethis::use_package("ggplot2")
usethis::use_package("testthat")
usethis::use_package("ggplot2")
usethis::use_package("dplyr")
usethis::use_package("knitr")
usethis::use_package("DT")
