
::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot001_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot001")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot002_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot002")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot003_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot003")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot004_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot004")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot005_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot005")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot006_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot006")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot007_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot007")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot008_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot008")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot009_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot009")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot010_residuals")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_residuals_plot010")
my_super_list[vector_obj]
```
:::
:::

***

