::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot001_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot001")
my_super_list[vector_obj]
```
:::
:::

***



::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot002_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot002")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot003_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot003")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot004_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot004")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot005_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot005")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot006_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot006")
my_super_list[vector_obj]
```
:::
:::

***

::: {.columns}
::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("plot007_factor")
my_super_list[[vector_obj]]
```
:::

::: {.column width="50%"}
```{r}
#| warning: false
#| echo: false

vector_obj <- c("df_table_factor_plot007")
my_super_list[vector_obj]
```
:::
:::

***


